mysite/cart/urls.py
from django.urls import include, path
from . import views

app_name = 'cart'
urlpatterns = [
	path('cart_detail/', views.cart_detail, name='cart_detail'),
	path('cart_add/<product_id>/', views.cart_add, name = 'cart_add'),
	path('cart_remove/<product_id>/', views.cart_remove, name = 'cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('orders/',include('orders.urls')),
	path('shop/',include('shop.urls')),
    path('admin/', admin.site.urls),
	path('cart/',include('cart.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.urls import include, path
from . import views


app_name = 'orders'
urlpatterns = [
    path('order_create/', views.order_create, name='order_create'),
	path('history/', views.history, name='history'),
]

mysite/shop/urls.py
from django.urls import include, path
from . import views

app_name = 'shop'
urlpatterns = [
	path('', views.index, name='index'),
	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logoutView, name = 'logout'),
	path('product_list/', views.product_list, name = 'product_list'),
	path('product_list/<category_slug>/', views.product_list, name = 'product_list_by_category'),
	path('product_detail/<id>/<slug>/', views.product_detail, name = 'product_detail'),
]

mysite/cart/models.py
from django.db import models

# Create your models here.

mysite/cart/forms.py
from django import forms
from django.utils import timezone
from django.forms import ModelForm


QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/cart/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django import forms
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.urls import reverse
from django.template import RequestContext
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm



@require_POST
#@csrf_protect
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cf = CartAddProductForm(request.POST)
    if cf.is_valid():
        cd = cf.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')



#@csrf_protect
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')



#@csrf_protect
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

mysite/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Shopping Cart Detail
{% endblock %}

{% block content %}
<h1>welcome: {{user.username}} !</h1>
    <p><a href ="{% url 'shop:logout' %}">logout</a></p>
	{% if user%}
		<p><a href ="{% url 'orders:history' %}">order history</a></p>
	{% endif %}

    <div style = "color:brown">
    <h1>Shopping Cart Detail</h1>
	</div>
    <table class="cart">
        <thead>
            <tr>
                <th>Photo</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Delete</th>
                <th>Unit Price</th>                
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.jpg" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
				<form action="{% url "cart:cart_add" product.id %}" method="post">
				{{ item.update_quantity_form.quantity }}
				{{ item.update_quantity_form.update }}
				<input type="submit" value="Modify">
				</form>
				</td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Delete</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Cart Subtotal</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">to Continue Shopping</a>
       <a href="{% url "orders:order_create" %}" class="button">
	   Proceed to Checkout
	   </a> 
    </p>
{% endblock %}