mysite/cart/urls.py
from django.urls import include, path
from . import views

app_name = 'cart'
urlpatterns = [
	path('cart_detail/', views.cart_detail, name='cart_detail'),
	path('cart_add/<product_id>/', views.cart_add, name = 'cart_add'),
	path('cart_remove/<product_id>/', views.cart_remove, name = 'cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('orders/',include('orders.urls')),
	path('shop/',include('shop.urls')),
    path('admin/', admin.site.urls),
	path('cart/',include('cart.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.urls import include, path
from . import views


app_name = 'orders'
urlpatterns = [
    path('order_create/', views.order_create, name='order_create'),
	path('history/', views.history, name='history'),
]

mysite/shop/urls.py
from django.urls import include, path
from . import views

app_name = 'shop'
urlpatterns = [
	path('', views.index, name='index'),
	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logoutView, name = 'logout'),
	path('product_list/', views.product_list, name = 'product_list'),
	path('product_list/<category_slug>/', views.product_list, name = 'product_list_by_category'),
	path('product_detail/<id>/<slug>/', views.product_detail, name = 'product_detail'),
]

mysite/shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return str(self.name)

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
	category = models.ForeignKey(Category, related_name = 'products', on_delete = models.CASCADE,)
	name = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=20, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)

	class Meta:
		ordering = ('name',)

	def __str__(self):
		return str(self.name)

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

mysite/shop/forms.py
from django import forms
from django.utils import timezone
from django.forms import ModelForm
from shop.models import User

class RegisterForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()

    def save(self,commit = True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password']
        )
        return user



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

mysite/shop/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django import forms
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.urls import reverse
from django.template import RequestContext
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

from .forms import RegisterForm, LoginForm
from .models import Category, Product
from cart.forms import CartAddProductForm


MIN_PASSWORD_LENGTH = 6



#@csrf_protect
def index(request):
    return render(request,'index.html')



#@csrf_protect
def register(request):
	if request.method =='POST':
		rf = RegisterForm(request.POST)
		if rf.is_valid():
			cd = rf.cleaned_data
			if User.objects.filter(username = cd['username']).exists():
				print('username already exists!')
				error_msg = "username already exists. Please pick another one."
				return render_to_response('register.html', {'rf': rf, 'error_msg': error_msg})
			if len(cd['password']) < MIN_PASSWORD_LENGTH:
				print('Password is too short!')
				error_msg = "Password is too short! Please enter a password longer than 6 chars."
				return render_to_response('register.html', {'rf': rf, 'error_msg': error_msg})
			rf.save()
			user = authenticate(username = cd['username'],password = cd['password'])
			auth_login(request,user)
			return redirect('shop:login')
	else:
		rf = RegisterForm()
	return render(request,"register.html",{'rf':rf})


#@csrf_exempt
#@csrf_protect
def login(request):
	if request.method == 'POST':
		lf = LoginForm(request.POST)
		if lf.is_valid():
			cd = lf.cleaned_data
			user = authenticate(request,username = cd['username'],password = cd['password'])
			if user is not None:
				auth_login(request,user)
				return render(request, 'product_list.html', {'category_slug':None})
#return render_to_response("product_list.html", category_slug=None)
			else:
				error_msg = "Please enter the correct username and password."
				return render_to_response('login.html',{'lf':lf,'error_msg': error_msg})
	else:
		lf = LoginForm()
	return render_to_response('login.html',{'lf':lf})
'''
@csrf_protect
def login(request):
    if request.method == 'POST':
        lf = LoginForm(request.POST)
        if lf.is_valid():
            cd = lf.cleaned_data
            user = authenticate(request,username = cd['username'],password = cd['password'])
            if user is not None:
                auth_login(request,user)
				return redirect('shop:product_list')
#return render(request, 'product_list.html', context=RequestContext(request))
            else:
                error_msg = "Please enter the correct username and password."
                return render_to_response('login.html',{'lf':lf,'error_msg': error_msg})
    else:
        lf = LoginForm()
    return render_to_response('login.html',{'lf':lf})
'''


#@csrf_protect
@login_required
def logoutView(request):
    logout(request)
    return redirect(reverse('shop:login'))


#@csrf_exempt
#@csrf_protect
#@login_required
def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.all()
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	content = {
		'category': category,
		'categories': categories,
		'products': products
	}
	return render(request, "product_list.html", content)



#@csrf_protect
def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug)
	cart_product_form = CartAddProductForm()
	content = {
		'product': product,
		'cart_product_form': cart_product_form
	}
	return render(request, "product_detail.html", content)

mysite/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<center>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}Welcome to Liang's Online Shop{% endblock %}</title>
</head>
<body>
	<body style="background: #ffffff url({% static "img.jpg" %})">
    <div id="header">
        <a href="/shop/product_list" class="logo">Welcome to Liang's Online Shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
        	{% with total_items=cart|length %}
        		{% if cart|length > 0 %}
            		Your Shopping Cart:
            		<a href="{% url "cart:cart_detail" %}">
                		{{ total_items }} item{{ total_items|pluralize }},
                		${{ cart.get_total_price }}
            		</a>
        		{% else %}
            		Your Shopping Cart is Empty
        		{% endif %}
    		{% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/shop/templates/index.html
{% load static %}
<body>
<center>
<body style="background: #ffffff url({% static "img.jpg" %})">
<div style="color:navy">
<h1>Welcome to Liang's Online Shop</h1>
</div>
<!--
  <div class="slogan">
  <div style = "color:brown">
    <p>Visit Liang's online shop as a tourist</p>
  </div>
  <div class="input_container">
    <form action="/shop/product_list/">
      <input type="submit" value="OK" class="fancy create_account" />
    </form>
  </div>
-->
    <a href="{% url 'shop:login' %}">Login</a><br>
    <a href="{% url 'shop:register' %}">Register</a>
</body>

mysite/shop/templates/login.html
{% load static %}
<html>
<center>
{% block title %}<h1>Welcome to Liang's Online Shop</h1>{% endblock %}
{% block body %}
<body style="background: #ffffff url({% static "img.jpg" %})">
<h2>Please Login：</h2>

{% if error_msg %}
<div style = "color:red">
  <h3>{{error_msg}}</h3>
  </div>
{% endif %}

<form method = 'post' enctype="multipart/form-data">
    {{lf.as_p}}
        <input type="submit" value = "Submit" />
</form>
  <div class="slogan">
    <p>Return to Register</p>
  </div>
  <div class="input_container">
    <form action="/shop/register/">
      <input type="submit" value="OK" class="fancy create_account" />
    </form>
  </div>
<!--
  <div class="slogan">
    <p>Visit Liang's online shop as a tourist</p>
  </div>
  <div class="input_container">
    <form action="/shop/product_list/">
      <input type="submit" value="OK" class="fancy create_account" />
    </form>
  </div>
-->
{% endblock %}
</html>

mysite/shop/templates/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<h1>welcome: {{user.username}} !</h1>
    <p><a href ="{% url 'shop:logout' %}">logout</a></p>
    {% if user%}
	    <p><a href ="{% url 'orders:history' %}">order history</a></p>
	{% endif %}

    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.jpg" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
            {{ product.description|linebreaks }}
		<form action="{% url "cart:cart_add" product.id %}" method="post">
		{{ cart_product_form }}
		<input type="submit" value="Add to cart">
		</form>
    </div>
{% endblock %}

mysite/shop/templates/product_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<h1>welcome: {{user.username}} !</h1>
    <p><a href ="{% url 'shop:logout' %}">logout</a></p>
    {% if user%}
	    <p><a href ="{% url 'orders:history' %}">order history</a></p>
	{% endif %}

    <div id="sidebar">
        <h3>Product Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.jpg" %}{% endif %}">
                </a><br>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %} 

mysite/shop/templates/register.html
{% load static %}
<html>
<center>
<head>
    {% block title %}<h1>Welcome to Liang's Online Shop</h1>{% endblock %}
</head>

<body>
<body style="background: #ffffff url({% static "img.jpg" %})">
<h2>Please Register</h2>
<div style="color:red">
{% if error_msg %}
    <h3>{{error_msg}}</h3>
{% endif %}
</div>
  <form method = 'post' enctype="multipart/form-data">
  {{rf.as_p}}
  <input type="submit" value = "OK" />
  </form>
  {% if messages %}
  <ulclass="messages">
    {%for message in messages %}
    <li{%if message.tags %} class="{{ message.tags }}"{% endif %}>{{message }}</li>
    {%endfor %}
  </ul>
  {% endif %}
  <div class="slogan">
    <p>Already have an account and login now?</p>
  </div>
  <div class="input_container">
    <form action="/shop/login/">
      <input type="submit" value="Yes" class="fancy create_account" />
    </form>
  </div>
<!--
  <div class="slogan">
    <p>Visit Liang's online shop as a tourist</p>
  </div>
  <div class="input_container">
    <form action="/shop/product_list/">
      <input type="submit" value="OK" class="fancy create_account" />
    </form>
  </div>
-->
</body>

</html>